### ISSUE TITLE
wpaint cant save a image whit a background image in google chrome

### ISSUE THREAD

**Issue by luysk8** [websanova/wPaint#11]
hello Google chrome does not  support a paint.js cannot save a image with an background  but can save a image with a preload images

**Comment by avernet** [comment]
Unless I misunderstand the bug report, I am not experimenting the same problem. For instance, in the [live demo](http://www.websanova.com/plugins/paint), from Chrome, I can:
1. Draw something in the second wPaint
2. From the Dev Tools console, save it: `i =  $('#wPaint2').wPaint('image')`
3. Restore this in the first wPaint, which doesn't have a background: `$('#wPaint1').wPaint('image', i)`

@websanova, I suggest closing this, unless @luysk8 can provide a test case.

**Comment by luysk8** [comment]
in my case if I keep the image to put the img within a div

**Comment by websanova** [comment]
I don't think you can load the image directly into a div.  You can load it into an `<img>` tag though, check the example on the live site.  If you wanted to do it into a div as a background or something, you would need to save the image on your server first.

**Comment by avernet** [comment]
If you want to load the image into a `div` instead of an `img`, say because this is the markup you have to work with, you can do so using a background image in CSS. CSS's `url()` also supports the data URIs, and you can dynamically add CSS to your page. I created [an example](https://dl.dropbox.com/u/6900/resources/20130118-background.html) that shows this in action, also to convince me that this indeed works :).

**Comment by luysk8** [comment]
awesome :) :+1:

**Comment by Rajagunasekaran** [comment]
me also got same issue, i load image directly from Google drive using get web content URL()
but i can't get image data from the paint area it's not response but image is there
