### ISSUE TITLE
remove wPaint element

### ISSUE THREAD

**Issue by deJong-IT** [websanova/wPaint#4]
Hi,

Is it possible to remove the wPaint element?

I'm using ajax to load the body, and init wPaint.
But how to remove it? If I remove the main element, the menu is still there.

I can't find a remove() or destroy() method, but maybe i'm not looking in the right place.

Thanks for the great plugin.

Jeroen

**Comment by websanova** [comment]
I will have to add a destroy method, but for now you can just do
$('._wPaint_menu').remove();

**Comment by deJong-IT** [comment]
Thanks!

**Comment by bvempalli1986** [comment]
did you have any thing to remove all the functionality after paint once i am done. And load it when i need it. like
removepaint button remove whole functionality or addpaint for adding whole paint functionality back when needed. Please let me know as soon as possible so that i can use it in my demo.
