### ISSUE TITLE
Disapeared all palette icon after upgrade.

### ISSUE THREAD

**Issue by azzureal** [websanova/wPaint#46]
So i just uploaded demo, but the same.

**Comment by websanova** [comment]
Can you please provide some more information about what you're doing.  Also double check the paths to the images.

**Comment by azzureal** [comment]
Thank for your reply.

It's my honor.

I just uploaded all without modification.

Previous version is OK.

http://hostingis.com/wpaint/

---

 보낸 사람: websanova notifications@github.com
받는 사람: websanova/wPaint wPaint@noreply.github.com 
참조: azzureal kenelpc@yahoo.com 
보낸 시간: 2013년 9월 13일(금요일) 1:07 오후
제목: Re: [wPaint] Disapeared all palette icon after upgrade. (#46)

Can you please provide some more information about what you're doing.  Also double check the paths to the images.

**Comment by websanova** [comment]
The images have absolute paths from the root, so if you look at the path
for the icons they are like so:

404 Not Found:  http://hostingis.com/plugins/main/img/icons-menu-main.png

Since the icons are actually under the `wpaint/` root, so if we go to:

http://hostingis.com/wpaint/plugins/main/img/icons-menu-main.png

You will see it.  Anyway, I have updated the plugin to include a `path`
option.  Get the latest version (2.1.1) and init wPaint with the `path`
option:

$('#elem').wPaint({path: '/wpaint/'});

That should work now.

**Comment by azzureal** [comment]
Thanks a lot.

---

 보낸 사람: websanova notifications@github.com
받는 사람: websanova/wPaint wPaint@noreply.github.com 
참조: azzureal kenelpc@yahoo.com 
보낸 시간: 2013년 9월 13일(금요일) 2:22 오후
제목: Re: [wPaint] Disapeared all palette icon after upgrade. (#46)

The images have absolute paths from the root, so if you look at the path 
for the icons they are like so: 

404 Not Found:  http://hostingis.com/plugins/main/img/icons-menu-main.png 

Since the icons are actually under the `wpaint/` root, so if we go to: 

http://hostingis.com/wpaint/plugins/main/img/icons-menu-main.png 

You will see it.  Anyway, I have updated the plugin to include a `path` 
option.  Get the latest version (2.1.1) and init wPaint with the `path` 
option: 

$('#elem').wPaint({path: '/wpaint/'}); 

That should work now.
