### ISSUE TITLE
Menus and canvas in the same 'box'

### ISSUE THREAD

**Issue by luiscruz** [websanova/wPaint#9]
Hi again!

In my application I'm fading out some divs before the canvas.
Unfortunately, it changes the relative position between canvas and the menu.

A possible solution would be having an option in which the menu wouldn't be draggable, and would be generated right before the canvas. (but it would still have the problem with the text menu).

Another way could be to refactor the MainMenu:generate method, separating the code for positioning the menus in a new method. Then, the new could be used in this case.

**Comment by luiscruz** [comment]
what do you think?

**Comment by websanova** [comment]
I have some ideas, will get to this soon.

**Comment by luiscruz** [comment]
cool :+1: thanks

**Comment by Chris109** [comment]
Hello

I have kind of the same request.
I would want to get the menu right above the paint area, and not floating over the page.

Any idea how to do this easily?

ex:
< div >
< div class=menu >My buttons</ div >
< div id='wPaint' ></ div >
< /div >

**Comment by websanova** [comment]
Okay, I think the issue came up in situations where the canvas moved around, as in situations where it is centered on the page.  I've update the menu to be relative to the canvas not to the page, so it will move with the canvas and always stay relative to it.  Just grab the latest version, for the updates.

**Comment by luiscruz** [comment]
Working, thanks! :+1:
